test:
	cd chapter01; python test.py
	cd chapter03; python test.py
	cd chapter04; python test.py
	cd chapter05; python test.py
	cd chapter06; python test.py
	cd chapter07; python test.py
	cd chapter08; python test.py
	cd chapter09; python test.py
	cd chapter11; python test.py
	cd chapter12; python test.py

rst:
	cd chapter01; python test.py --format=rest > README.rst
	cd chapter03; python test.py --format=rest > README.rst
	cd chapter04; python test.py --format=rest > README.rst
	cd chapter05; python test.py --format=rest > README.rst
	cd chapter06; python test.py --format=rest > README.rst
	cd chapter07; python test.py --format=rest > README.rst
	cd chapter08; python test.py --format=rest > README.rst
	cd chapter09; python test.py --format=rest > README.rst
	cd chapter11; python test.py --format=rest > README.rst
	cd chapter12; python test.py --format=rest > README.rst
