test:
	cd section1; python test.py
	cd section3; python test.py
	cd section4; python test.py
	cd section5; python test.py
	cd section6; python test.py
	cd section7; python test.py
	cd section8; python test.py
	cd section9; python test.py
	cd section11; python test.py
	cd section12; python test.py

rst:
	cd section1; python test.py --format=rest > README.rst
	cd section3; python test.py --format=rest > README.rst
	cd section4; python test.py --format=rest > README.rst
	cd section5; python test.py --format=rest > README.rst
	cd section6; python test.py --format=rest > README.rst
	cd section7; python test.py --format=rest > README.rst
	cd section8; python test.py --format=rest > README.rst
	cd section9; python test.py --format=rest > README.rst
	cd section11; python test.py --format=rest > README.rst
	cd section12; python test.py --format=rest > README.rst
